projects:
  magical_meadow: {}
  serene_magic: {}
  super_snowflake: {}
  unit_0_setup: {}
  unit_1_data_preparation: {}
  unit_1_follow_along:
    path: unit_1_follow_along
  unit_2_training: {}
  unit_3_observability: {}
